DROP TABLE IF EXISTS pets CASCADE;

CREATE TABLE pets (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(50)NOT NULL,
  breed VARCHAR(50)NOT NULL,
  age INTEGER NOT NULL,
  sex VARCHAR(50)NOT NULL,
  size VARCHAR(50)NOT NULL,
  spayed_or_neutered BOOLEAN NOT NULL DEFAULT FALSE,
  city VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  photo_url VARCHAR(255) NOT NULL
);
